export interface SkillData {
  name: string;
  baseTrait: 'Strength' | 'Agility' | 'Knowledge' | 'Willpower' | 'Instinct' | 'Leadership' | 'Resolve';
  classes: string[];
}

export const allSkillsData: SkillData[] = [
  { name: 'Ambient Magic', baseTrait: 'Willpower', classes: ['ALL'] },
  { name: 'Athletics', baseTrait: 'Strength', classes: ['ALL'] },
  { name: 'Crystal Sciences', baseTrait: 'Knowledge', classes: ['Engineer', 'Phase-Craft Tecnician', 'Healer', 'Warlock', 'Druid'] },
  { name: 'Deception', baseTrait: 'Leadership', classes: ['ALL'] },
  { name: 'Diplomacy', baseTrait: 'Leadership', classes: ['ALL'] },
  { name: 'Dodge', baseTrait: 'Agility', classes: ['ALL'] },
  { name: 'First Aid', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'History', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Improved Instinct', baseTrait: 'Instinct', classes: ['ALL'] },
  { name: 'Intimidation', baseTrait: 'Strength', classes: ['ALL'] },
  { name: 'Iron Will', baseTrait: 'Willpower', classes: ['ALL'] },
  { name: 'Ley Line Detection', baseTrait: 'Instinct', classes: ['ALL'] },
  { name: 'Medicine', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Metallurgy', baseTrait: 'Knowledge', classes: ['Engineer', 'Phase-craft Tecnician'] },
  { name: 'Perception', baseTrait: 'Instinct', classes: ['ALL'] },
  { name: 'Phase Space Navigation', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Pickpocket', baseTrait: 'Agility', classes: ['ALL'] },
  { name: 'Religion', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Riding', baseTrait: 'Agility', classes: ['ALL'] },
  { name: 'Rune Knowledge', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Survival', baseTrait: 'Instinct', classes: ['ALL'] },
  { name: 'Tactical', baseTrait: 'Knowledge', classes: ['Soldier', 'Engineer', 'Pilot', 'Phase-Craft Technician'] },
  { name: 'Inspiring Leader', baseTrait: 'Resolve', classes: ['ALL'] },
  { name: 'Skinning', baseTrait: 'Agility', classes: ['ALL'] },
  { name: 'Navigation-Land', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Navigation-Phase Space', baseTrait: 'Instinct', classes: ['Pilot', 'Phase-craft Technician'] },
  { name: 'Piloting', baseTrait: 'Agility', classes: ['Pilot'] },
  { name: 'Navigation-Dungeon', baseTrait: 'Instinct', classes: ['ALL'] },
  { name: 'Navigation-Sewers', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Navigation-Ocean', baseTrait: 'Knowledge', classes: ['ALL'] },
  { name: 'Forge Tender', baseTrait: 'Knowledge', classes: ['Engineer', 'Phase-craft Tecnician'] },
  { name: 'Masonry', baseTrait: 'Knowledge', classes: ['Engineer'] },
  { name: 'Navigation-Limbo', baseTrait: 'Instinct', classes: ['ALL'] },
  { name: 'Two-handed weapon mastery', baseTrait: 'Strength', classes: ['ALL'] },
  { name: 'Deft hands', baseTrait: 'Agility', classes: ['ALL'] },
  { name: 'Monk weapon mastery', baseTrait: 'Agility', classes: ['Monk'] },
  { name: 'Trap detection', baseTrait: 'Instinct', classes: ['Thief', 'Spy', 'Monster Hunter'] },
  { name: 'Magical trap detection', baseTrait: 'Instinct', classes: ['Healer', 'Warlock', 'Druid', 'Magus acolyte', 'Spy'] },
  { name: 'Sense danger', baseTrait: 'Instinct', classes: ['Soldier', 'Engineer'] },
  { name: 'Trap engineer', baseTrait: 'Knowledge', classes: ['Engineer'] },
  { name: 'Carpentry', baseTrait: 'Knowledge', classes: ['Soldier', 'Engineer'] },
  { name: 'Barrier emplacement', baseTrait: 'Knowledge', classes: ['Soldier', 'Engineer'] },
  { name: 'Mechanical mastery', baseTrait: 'Knowledge', classes: ['Engineer', 'Pilot', 'Phase-craft tehnician'] },
  { name: 'Cobbler', baseTrait: 'Knowledge', classes: ['ALL'] },
];
